In [1]:
import xarray as xr
import numpy as np
import os
import matplotlib.pyplot as plt

In [6]:
# Load dataset
file1 = xr.open_dataset('~/Parameters/FjordModeling/Qsg_maxhs.nc')
file2 = xr.open_dataset('~/Parameters/FjordModeling/Qsg_minhs.nc')

Qsg = file1.Qsg.data
alp11_1 = file1.alpha11.data
alp11_1[alp11_1<0] = 0
alp22_1 = file1.alpha22.data
Qin1_maxhs = file1.Qin1.data
Qin2_maxhs = file1.Qin2.data
Qe1 = Qin1_maxhs-Qin2_maxhs
Qsm1 = file1.Qsm.data
Tsr1 = file1.Ts.data / file1.Ts_in.data
Tsre1 = file1.Ts_e.data / file1.Ts_in.data

alp11_2 = file2.alpha11.data
alp11_2[alp11_2<0] = 0
alp22_2 = file2.alpha22.data
Qin1_minhs = file2.Qin1.data
Qin2_minhs = file2.Qin2.data
Qe2 = Qin1_minhs-Qin2_minhs
Qsm2 = file2.Qsm.data
Tsr2 = file2.Ts.data / file2.Ts_in.data
Tsre2 = file2.Ts_e.data / file2.Ts_in.data

In [5]:
Qin1_maxhs, Qin2_maxhs, Qin1_minhs, Qin2_minhs

(array([ 1787.32853523,  5678.65757266,  6569.02992135,  7912.03856441,
        11592.02990997, 15643.50836207]),
 array([  275.37801987,  1645.49541834,  3082.03902451,  6282.10174435,
         9441.10105145, 13112.85427439]),
 array([  756.22594746,   821.58304835,  5108.53386557,  8776.80278027,
        12040.55202662, 16110.87600677]),
 array([ 104.79701145,   58.51639497,  716.84783278, 2423.74567441,
        3418.62995074, 4530.11227712]))

In [45]:
fig1 = plt.figure(figsize=(10,10))
#fig1.tight_layout()
#plt.grid(linestyle='--', linewidth=0.5)    
ax1 = fig1.add_subplot(221)
ax2 = fig1.add_subplot(222)
ax3 = fig1.add_subplot(223)
ax4 = fig1.add_subplot(224)

# Reflux coeff plot
ax1.plot(Qsg,alp11_1,'^-r', Qsg,alp22_1,'v-r', ms=8,lw=1.5)
ax1.plot(Qsg,alp11_2,'^-b', Qsg,alp22_2,'v-b', ms=8,lw=1.5)

line1 = plt.Line2D((0,1),(0,0), color='r', lw=1.5, linestyle='-')
line2 = plt.Line2D((0,1),(0,0), color='b', lw=1.5, linestyle='-')
marker1 = plt.Line2D((0,1),(0,0), color='k', marker='v', ms=8,linestyle='')
marker2 = plt.Line2D((0,1),(0,0), color='k', marker='^', ms=8,linestyle='') 
ax1.legend([line1,line2,marker1,marker2],[r'$h_s/h=0.12$',r'$h_s/h=0.04$',r'$\alpha_{11}$', r'$\alpha_{22}$'],
              loc='best', fontsize=12)

ax1.grid(linestyle='--', linewidth=0.5)
ax1.set_ylabel(r'$\alpha$',size = 15)
ax1.tick_params(direction='in', labelsize=15)
ax1.set_title(r'(a) Reflux Coefficient', loc='left', size=15, weight='bold')


# Add path for uncertain values
from matplotlib.patches import Rectangle
rect1 = Rectangle((0,-.02),150,.82,facecolor='k',alpha=0.2)
# Add the patch to the Axes
ax1.add_patch(rect1)


# Qe plot
ax2.plot(Qsg,Qe1/Qin1_maxhs,'o-r', Qsg,Qe2/Qin1_minhs,'o-b',ms=8, lw=1.5)
ax2.legend([r'$h_s/h=0.12$',r'$h_s/h=0.04$'],loc='right', fontsize=12)
ax2.set_ylabel(r'$Q_e/Q^1_{in}$',size = 15)
ax2.grid(linestyle='--', linewidth=0.5)
ax2.tick_params(direction='in', labelsize=15)
ax2.set_title(r'(b) Entrainment Over Sill', loc='left', size=15, weight='bold')

# Add path for uncertain values
rect2 = Rectangle((0,.5),150,.45,facecolor='k',alpha=0.2)
# Add the patch to the Axes
ax2.add_patch(rect2)



# T_fjord/T_shelf plot
ax3.plot(Qsg,Tsre1,'o-r', Qsg,Tsre2,'o-b',ms=8, lw=1.5)
ax3.legend([r'$h_s/h=0.12$',r'$h_s/h=0.04$'],loc='right', fontsize=12)
ax3.set_xlabel(r'$Q_{sg}\;[m^3/s]$',size = 15)
ax3.set_ylabel(r'$T_{fjord}/T_{shelf}$',size =15)
ax3.grid(linestyle='--', linewidth=0.5)
ax3.tick_params(direction='in', labelsize=15)
ax3.set_title(r'(c) Deep-Fjord Temperature', loc='left', size=15, weight='bold')

# Add path for uncertain values
rect3 = Rectangle((0,.5),150,.45,facecolor='k',alpha=0.2)
# Add the patch to the Axes
ax3.add_patch(rect3)


# Qsm plot
ax4.plot(Qsg,Qsm1,'o-r', Qsg,Qsm2,'o-b',ms=8, lw=1.5)
ax4.legend([r'$h_s/h=0.12$',r'$h_s/h=0.04$'],loc='right', fontsize=12)
ax4.set_xlabel(r'$Q_{sg}\;[m^3/s]$',size = 15)
ax4.set_ylabel(r'$Q_{sm}\;[m^3/s]$',size = 15)
ax4.grid(linestyle='--', linewidth=0.5)
ax4.tick_params(direction='in', labelsize=15)
ax4.set_title(r'(d) Submarine Melting', loc='left', size=15, weight='bold')

# set the spacing between subplots
plt.subplots_adjust(left=0.1,
                    bottom=0.1, 
                    right=0.9, 
                    top=0.9, 
                    wspace=0.25, 
                    hspace=0.2)

In [46]:
fig_path ="/home/1959/Jupyter_Figs/FjordModeling/"
if not os.path.exists(fig_path):
    os.makedirs(fig_path)
fig1.savefig(fig_path + '/6-QsgCase.png', dpi=200, bbox_inches='tight') 