In [1]:
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import interp2d
from scipy.interpolate import interp1d

In [2]:
state0 = xr.open_dataset('/Users/weiyang/Desktop/sill12/state_002.nc')
state = state0.isel(Y = range(1,10)) # Remove the boundary walls in y direction

In [67]:
xloc = 27# Location in x-axsis 0~50

z1 = np.arange(-1.5,-150,-3)
z0 = state.Z.data
y0 = state.Y.data

#y, z = np.meshgrid(y0,z0)
#yi, zi = np.meshgrid(y0,z1)
from scipy.interpolate import griddata



import numpy.ma as ma

u = state.U.isel(T = 41, Xp1 = xloc).data
u_corr = ma.masked_values (u, 0.)
f_u = interp2d(y0, z0, u_corr) # Interpolate in Z direction
u_interp = f_u(y0, z1)
#zi = griddata((z,y),u_corr,(zi,yi),method='linear')
Q1 = u[:10,:].sum() * 100
Q2 = u[10:20,:].sum() * 200
Q3 = u[20:30,:].sum() * 300
Q4 = u[30:40,:].sum() * 800
Q5 = u[40:,:].sum() * 1600
Qsum = Q1 + Q2 + Q3 + Q4 + Q5

uy = np.empty(len(y0))
for i in range(len(y0)):
    f = interp1d(z0, u_corr[:,i],bounds_error=False)
    us[i] = np.interp(-z1,-z0,u_corr[:,i]).sum()

u_interp[u_interp > 0].sum(), u_interp[u_interp < 0].sum(), Qsum

(3.4702807754511014, -2.820221679400261, 179.6465277671814)

In [69]:
u_interp.sum()

0.6500590960508404

In [4]:
z0,z1,uy

(array([  -0.25,   -0.75,   -1.25,   -1.75,   -2.25,   -2.75,   -3.25,
          -3.75,   -4.25,   -4.75,   -5.5 ,   -6.5 ,   -7.5 ,   -8.5 ,
          -9.5 ,  -10.5 ,  -11.5 ,  -12.5 ,  -13.5 ,  -14.5 ,  -15.75,
         -17.25,  -18.75,  -20.25,  -21.75,  -23.25,  -24.75,  -26.25,
         -27.75,  -29.25,  -32.  ,  -36.  ,  -40.  ,  -44.  ,  -48.  ,
         -52.  ,  -56.  ,  -60.  ,  -64.  ,  -68.  ,  -74.  ,  -82.  ,
         -90.  ,  -98.  , -106.  , -114.  , -122.  , -130.  , -138.  ,
        -146.  ]),
 array([  -1.5,   -4.5,   -7.5,  -10.5,  -13.5,  -16.5,  -19.5,  -22.5,
         -25.5,  -28.5,  -31.5,  -34.5,  -37.5,  -40.5,  -43.5,  -46.5,
         -49.5,  -52.5,  -55.5,  -58.5,  -61.5,  -64.5,  -67.5,  -70.5,
         -73.5,  -76.5,  -79.5,  -82.5,  -85.5,  -88.5,  -91.5,  -94.5,
         -97.5, -100.5, -103.5, -106.5, -109.5, -112.5, -115.5, -118.5,
        -121.5, -124.5, -127.5, -130.5, -133.5, -136.5, -139.5, -142.5,
        -145.5, -148.5]),
 array([ 300.,  500.,  700

In [38]:
z1[:-1]

array([  -1.5,   -4.5,   -7.5,  -10.5,  -13.5,  -16.5,  -19.5,  -22.5,
        -25.5,  -28.5,  -31.5,  -34.5,  -37.5,  -40.5,  -43.5,  -46.5,
        -49.5,  -52.5,  -55.5,  -58.5,  -61.5,  -64.5,  -67.5,  -70.5,
        -73.5,  -76.5,  -79.5,  -82.5,  -85.5,  -88.5,  -91.5,  -94.5,
        -97.5, -100.5, -103.5, -106.5, -109.5, -112.5, -115.5, -118.5,
       -121.5, -124.5, -127.5, -130.5, -133.5, -136.5, -139.5, -142.5,
       -145.5])

In [ ]:
z0 = state.Z.data
y0 = state.Y.data
yy, zz = np.meshgrid(y0, z0)
np.shape(yy)

In [ ]:
np.meshgrid?